version: "3.8"

services:
  nodejs-server:
    build: .
    ports:
      - "5000:5000"
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - PORT=5000
      - CLERK_API_KEY=${CLERK_API_KEY}
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - mongodb

  flask-gemini:
    build:
      context: ./Flask Backend
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    volumes:
      - ./Flask Backend:/app

  flask-youtube:
    build:
      context: ./Flask Backend
      dockerfile: Dockerfile
    ports:
      - "5002:5002"
    volumes:
      - ./Flask Backend:/app
    command: python app1.py

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
