version: "3.8"

services:
  client:
    build:
      context: ./Client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=http://nodejs-server:5000
      - VITE_GEMINI_URL=http://flask-gemini:5001
      - VITE_YOUTUBE_URL=http://flask-youtube:5002
    volumes:
      - ./Client:/app
      - /app/node_modules
    depends_on:
      - nodejs-server

  nodejs-server:
    build:
      context: ./Server
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - PORT=5000
      - CLERK_API_KEY=${CLERK_API_KEY}
    volumes:
      - ./Server:/app
      - /app/node_modules
    depends_on:
      - mongodb

  flask-gemini:
    build:
      context: ./Server/Flask Backend
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    volumes:
      - ./Server/Flask Backend:/app

  flask-youtube:
    build:
      context: ./Server/Flask Backend
      dockerfile: Dockerfile
    ports:
      - "5002:5002"
    environment:
      - FLASK_APP=app1.py
      - FLASK_ENV=development
    volumes:
      - ./Server/Flask Backend:/app
    command: python app1.py

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
